/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BuildInfo { 'version' : string, 'backendTimestamp' : string }
export interface CycleSchema {
  'cycleType' : string,
  'description' : string,
  'schemaEntries' : Array<CycleSchemaEntry>,
  'cycleSchemaId' : string,
}
export interface CycleSchemaEntry {
  'patternType' : string,
  'description' : string,
  'entries' : Array<CycleSchemaEntry>,
  'customPattern' : Array<boolean>,
  'cycleSchemaId' : string,
}
export interface LayerEntry {
  'layerId' : string,
  'subLayers' : Array<LayerEntry>,
  'description' : string,
  'layerType' : string,
  'timeEstimateInMinutes' : [] | [bigint],
}
export interface RestEntry {
  'restId' : string,
  'timeRangeInMinutes' : string,
  'autoSaved' : boolean,
  'description' : string,
  'restType' : string,
  'autoCompletedTime' : boolean,
  'percentage' : bigint,
}
export interface RoutineLayerConfig {
  'layerConfig' : LayerEntry,
  'routineId' : string,
}
export interface SubTaskEntry {
  'status' : TaskStatus,
  'description' : string,
  'subTaskId' : string,
  'timeEstimateInMinutes' : [] | [bigint],
}
export interface TaskDetails {
  'status' : TaskStatus,
  'restEntries' : Array<RestEntry>,
  'allSubTasksCompleted' : boolean,
  'description' : string,
  'subTasks' : Array<SubTaskEntry>,
  'taskId' : string,
  'parentTaskId' : [] | [string],
  'timeEstimateInMinutes' : [] | [bigint],
}
export type TaskStatus = { 'notStarted' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface TimelineEvent {
  'id' : string,
  'startTime' : bigint,
  'endTime' : [] | [bigint],
  'details' : { 'routineLayerConfig' : RoutineLayerConfig } |
    { 'cycleSchema' : CycleSchema } |
    { 'rest' : RestEntry } |
    { 'task' : TaskDetails },
  'eventType' : TimelineEventType,
}
export type TimelineEventType = { 'task' : null } |
  { 'sleep' : null } |
  { 'stats' : null } |
  { 'routine' : null } |
  { 'special' : null };
export interface UserProfile { 'name' : string, 'createdAt' : bigint }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEvent' : ActorMethod<[TimelineEvent], undefined>,
  'adminGetUserEvents' : ActorMethod<[Principal], Array<TimelineEvent>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteEvent' : ActorMethod<[string], undefined>,
  'getActiveEvents' : ActorMethod<[], Array<TimelineEvent>>,
  'getAllEvents' : ActorMethod<[], Array<TimelineEvent>>,
  'getBuildInfo' : ActorMethod<[], BuildInfo>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEvent' : ActorMethod<[string], TimelineEvent>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateEvent' : ActorMethod<[TimelineEvent], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];