/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CycleSchemaEntry = IDL.Rec();
export const LayerEntry = IDL.Rec();
export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
LayerEntry.fill(
  IDL.Record({
    'layerId' : IDL.Text,
    'subLayers' : IDL.Vec(LayerEntry),
    'description' : IDL.Text,
    'layerType' : IDL.Text,
    'timeEstimateInMinutes' : IDL.Opt(IDL.Nat),
  })
);
export const RoutineLayerConfig = IDL.Record({
  'layerConfig' : LayerEntry,
  'routineId' : IDL.Text,
});
CycleSchemaEntry.fill(
  IDL.Record({
    'patternType' : IDL.Text,
    'description' : IDL.Text,
    'entries' : IDL.Vec(CycleSchemaEntry),
    'customPattern' : IDL.Vec(IDL.Bool),
    'cycleSchemaId' : IDL.Text,
  })
);
export const CycleSchema = IDL.Record({
  'cycleType' : IDL.Text,
  'description' : IDL.Text,
  'schemaEntries' : IDL.Vec(CycleSchemaEntry),
  'cycleSchemaId' : IDL.Text,
});
export const RestEntry = IDL.Record({
  'restId' : IDL.Text,
  'timeRangeInMinutes' : IDL.Text,
  'autoSaved' : IDL.Bool,
  'description' : IDL.Text,
  'restType' : IDL.Text,
  'autoCompletedTime' : IDL.Bool,
  'percentage' : IDL.Nat,
});
export const TaskStatus = IDL.Variant({
  'notStarted' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const SubTaskEntry = IDL.Record({
  'status' : TaskStatus,
  'description' : IDL.Text,
  'subTaskId' : IDL.Text,
  'timeEstimateInMinutes' : IDL.Opt(IDL.Nat),
});
export const TaskDetails = IDL.Record({
  'status' : TaskStatus,
  'restEntries' : IDL.Vec(RestEntry),
  'allSubTasksCompleted' : IDL.Bool,
  'description' : IDL.Text,
  'subTasks' : IDL.Vec(SubTaskEntry),
  'taskId' : IDL.Text,
  'parentTaskId' : IDL.Opt(IDL.Text),
  'timeEstimateInMinutes' : IDL.Opt(IDL.Nat),
});
export const TimelineEventType = IDL.Variant({
  'task' : IDL.Null,
  'sleep' : IDL.Null,
  'stats' : IDL.Null,
  'routine' : IDL.Null,
  'special' : IDL.Null,
});
export const TimelineEvent = IDL.Record({
  'id' : IDL.Text,
  'startTime' : IDL.Nat64,
  'endTime' : IDL.Opt(IDL.Nat64),
  'details' : IDL.Variant({
    'routineLayerConfig' : RoutineLayerConfig,
    'cycleSchema' : CycleSchema,
    'rest' : RestEntry,
    'task' : TaskDetails,
  }),
  'eventType' : TimelineEventType,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BuildInfo = IDL.Record({
  'version' : IDL.Text,
  'backendTimestamp' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : IDL.Nat64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEvent' : IDL.Func([TimelineEvent], [], []),
  'adminGetUserEvents' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(TimelineEvent)],
      ['query'],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteEvent' : IDL.Func([IDL.Text], [], []),
  'getActiveEvents' : IDL.Func([], [IDL.Vec(TimelineEvent)], ['query']),
  'getAllEvents' : IDL.Func([], [IDL.Vec(TimelineEvent)], ['query']),
  'getBuildInfo' : IDL.Func([], [BuildInfo], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEvent' : IDL.Func([IDL.Text], [TimelineEvent], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateEvent' : IDL.Func([TimelineEvent], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CycleSchemaEntry = IDL.Rec();
  const LayerEntry = IDL.Rec();
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  LayerEntry.fill(
    IDL.Record({
      'layerId' : IDL.Text,
      'subLayers' : IDL.Vec(LayerEntry),
      'description' : IDL.Text,
      'layerType' : IDL.Text,
      'timeEstimateInMinutes' : IDL.Opt(IDL.Nat),
    })
  );
  const RoutineLayerConfig = IDL.Record({
    'layerConfig' : LayerEntry,
    'routineId' : IDL.Text,
  });
  CycleSchemaEntry.fill(
    IDL.Record({
      'patternType' : IDL.Text,
      'description' : IDL.Text,
      'entries' : IDL.Vec(CycleSchemaEntry),
      'customPattern' : IDL.Vec(IDL.Bool),
      'cycleSchemaId' : IDL.Text,
    })
  );
  const CycleSchema = IDL.Record({
    'cycleType' : IDL.Text,
    'description' : IDL.Text,
    'schemaEntries' : IDL.Vec(CycleSchemaEntry),
    'cycleSchemaId' : IDL.Text,
  });
  const RestEntry = IDL.Record({
    'restId' : IDL.Text,
    'timeRangeInMinutes' : IDL.Text,
    'autoSaved' : IDL.Bool,
    'description' : IDL.Text,
    'restType' : IDL.Text,
    'autoCompletedTime' : IDL.Bool,
    'percentage' : IDL.Nat,
  });
  const TaskStatus = IDL.Variant({
    'notStarted' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const SubTaskEntry = IDL.Record({
    'status' : TaskStatus,
    'description' : IDL.Text,
    'subTaskId' : IDL.Text,
    'timeEstimateInMinutes' : IDL.Opt(IDL.Nat),
  });
  const TaskDetails = IDL.Record({
    'status' : TaskStatus,
    'restEntries' : IDL.Vec(RestEntry),
    'allSubTasksCompleted' : IDL.Bool,
    'description' : IDL.Text,
    'subTasks' : IDL.Vec(SubTaskEntry),
    'taskId' : IDL.Text,
    'parentTaskId' : IDL.Opt(IDL.Text),
    'timeEstimateInMinutes' : IDL.Opt(IDL.Nat),
  });
  const TimelineEventType = IDL.Variant({
    'task' : IDL.Null,
    'sleep' : IDL.Null,
    'stats' : IDL.Null,
    'routine' : IDL.Null,
    'special' : IDL.Null,
  });
  const TimelineEvent = IDL.Record({
    'id' : IDL.Text,
    'startTime' : IDL.Nat64,
    'endTime' : IDL.Opt(IDL.Nat64),
    'details' : IDL.Variant({
      'routineLayerConfig' : RoutineLayerConfig,
      'cycleSchema' : CycleSchema,
      'rest' : RestEntry,
      'task' : TaskDetails,
    }),
    'eventType' : TimelineEventType,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BuildInfo = IDL.Record({
    'version' : IDL.Text,
    'backendTimestamp' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : IDL.Nat64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEvent' : IDL.Func([TimelineEvent], [], []),
    'adminGetUserEvents' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TimelineEvent)],
        ['query'],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteEvent' : IDL.Func([IDL.Text], [], []),
    'getActiveEvents' : IDL.Func([], [IDL.Vec(TimelineEvent)], ['query']),
    'getAllEvents' : IDL.Func([], [IDL.Vec(TimelineEvent)], ['query']),
    'getBuildInfo' : IDL.Func([], [BuildInfo], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEvent' : IDL.Func([IDL.Text], [TimelineEvent], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateEvent' : IDL.Func([TimelineEvent], [], []),
  });
};

export const init = ({ IDL }) => { return []; };