/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BuildInfo {
    version: string;
    backendTimestamp: string;
}
export interface RoutineLayerConfig {
    layerConfig: LayerEntry;
    routineId: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface RestEntry {
    restId: string;
    timeRangeInMinutes: string;
    autoSaved: boolean;
    description: string;
    restType: string;
    autoCompletedTime: boolean;
    percentage: bigint;
}
export interface LayerEntry {
    layerId: string;
    subLayers: Array<LayerEntry>;
    description: string;
    layerType: string;
    timeEstimateInMinutes?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface CycleSchemaEntry {
    patternType: string;
    description: string;
    entries: Array<CycleSchemaEntry>;
    customPattern: Array<boolean>;
    cycleSchemaId: string;
}
export interface TimelineEvent {
    id: string;
    startTime: bigint;
    endTime?: bigint;
    details: {
        __kind__: "routineLayerConfig";
        routineLayerConfig: RoutineLayerConfig;
    } | {
        __kind__: "cycleSchema";
        cycleSchema: CycleSchema;
    } | {
        __kind__: "rest";
        rest: RestEntry;
    } | {
        __kind__: "task";
        task: TaskDetails;
    };
    eventType: TimelineEventType;
}
export interface TaskDetails {
    status: TaskStatus;
    restEntries: Array<RestEntry>;
    allSubTasksCompleted: boolean;
    description: string;
    subTasks: Array<SubTaskEntry>;
    taskId: string;
    parentTaskId?: string;
    timeEstimateInMinutes?: bigint;
}
export interface SubTaskEntry {
    status: TaskStatus;
    description: string;
    subTaskId: string;
    timeEstimateInMinutes?: bigint;
}
export interface CycleSchema {
    cycleType: string;
    description: string;
    schemaEntries: Array<CycleSchemaEntry>;
    cycleSchemaId: string;
}
export interface UserProfile {
    name: string;
    createdAt: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum TaskStatus {
    notStarted = "notStarted",
    completed = "completed",
    inProgress = "inProgress"
}
export enum TimelineEventType {
    task = "task",
    sleep = "sleep",
    stats = "stats",
    routine = "routine",
    special = "special"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addEvent(event: TimelineEvent): Promise<void>;
    adminGetUserEvents(user: Principal): Promise<Array<TimelineEvent>>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteEvent(id: string): Promise<void>;
    getActiveEvents(): Promise<Array<TimelineEvent>>;
    getAllEvents(): Promise<Array<TimelineEvent>>;
    getBuildInfo(): Promise<BuildInfo>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEvent(id: string): Promise<TimelineEvent>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateEvent(event: TimelineEvent): Promise<void>;
}
import type { CycleSchema as _CycleSchema, CycleSchemaEntry as _CycleSchemaEntry, LayerEntry as _LayerEntry, RestEntry as _RestEntry, RoutineLayerConfig as _RoutineLayerConfig, SubTaskEntry as _SubTaskEntry, TaskDetails as _TaskDetails, TaskStatus as _TaskStatus, TimelineEvent as _TimelineEvent, TimelineEventType as _TimelineEventType, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addEvent(arg0: TimelineEvent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEvent(to_candid_TimelineEvent_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEvent(to_candid_TimelineEvent_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async adminGetUserEvents(arg0: Principal): Promise<Array<TimelineEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetUserEvents(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetUserEvents(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n55(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n55(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteEvent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async getActiveEvents(): Promise<Array<TimelineEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveEvents();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveEvents();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEvents(): Promise<Array<TimelineEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEvents();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEvents();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBuildInfo(): Promise<BuildInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuildInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuildInfo();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvent(arg0: string): Promise<TimelineEvent> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvent(arg0);
                return from_candid_TimelineEvent_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvent(arg0);
            return from_candid_TimelineEvent_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateEvent(arg0: TimelineEvent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(to_candid_TimelineEvent_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(to_candid_TimelineEvent_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_CycleSchemaEntry_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CycleSchemaEntry): CycleSchemaEntry {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_CycleSchema_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CycleSchema): CycleSchema {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_LayerEntry_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LayerEntry): LayerEntry {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_RoutineLayerConfig_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoutineLayerConfig): RoutineLayerConfig {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_SubTaskEntry_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubTaskEntry): SubTaskEntry {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_TaskDetails_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskDetails): TaskDetails {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_TimelineEventType_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimelineEventType): TimelineEventType {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_TimelineEvent_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimelineEvent): TimelineEvent {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    startTime: bigint;
    endTime: [] | [bigint];
    details: {
        routineLayerConfig: _RoutineLayerConfig;
    } | {
        cycleSchema: _CycleSchema;
    } | {
        rest: _RestEntry;
    } | {
        task: _TaskDetails;
    };
    eventType: _TimelineEventType;
}): {
    id: string;
    startTime: bigint;
    endTime?: bigint;
    details: {
        __kind__: "routineLayerConfig";
        routineLayerConfig: RoutineLayerConfig;
    } | {
        __kind__: "cycleSchema";
        cycleSchema: CycleSchema;
    } | {
        __kind__: "rest";
        rest: RestEntry;
    } | {
        __kind__: "task";
        task: TaskDetails;
    };
    eventType: TimelineEventType;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        endTime: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.endTime)),
        details: from_candid_variant_n34(_uploadFile, _downloadFile, value.details),
        eventType: from_candid_TimelineEventType_n53(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    layerConfig: _LayerEntry;
    routineId: string;
}): {
    layerConfig: LayerEntry;
    routineId: string;
} {
    return {
        layerConfig: from_candid_LayerEntry_n37(_uploadFile, _downloadFile, value.layerConfig),
        routineId: value.routineId
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    layerId: string;
    subLayers: Array<_LayerEntry>;
    description: string;
    layerType: string;
    timeEstimateInMinutes: [] | [bigint];
}): {
    layerId: string;
    subLayers: Array<LayerEntry>;
    description: string;
    layerType: string;
    timeEstimateInMinutes?: bigint;
} {
    return {
        layerId: value.layerId,
        subLayers: from_candid_vec_n39(_uploadFile, _downloadFile, value.subLayers),
        description: value.description,
        layerType: value.layerType,
        timeEstimateInMinutes: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.timeEstimateInMinutes))
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cycleType: string;
    description: string;
    schemaEntries: Array<_CycleSchemaEntry>;
    cycleSchemaId: string;
}): {
    cycleType: string;
    description: string;
    schemaEntries: Array<CycleSchemaEntry>;
    cycleSchemaId: string;
} {
    return {
        cycleType: value.cycleType,
        description: value.description,
        schemaEntries: from_candid_vec_n42(_uploadFile, _downloadFile, value.schemaEntries),
        cycleSchemaId: value.cycleSchemaId
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    patternType: string;
    description: string;
    entries: Array<_CycleSchemaEntry>;
    customPattern: Array<boolean>;
    cycleSchemaId: string;
}): {
    patternType: string;
    description: string;
    entries: Array<CycleSchemaEntry>;
    customPattern: Array<boolean>;
    cycleSchemaId: string;
} {
    return {
        patternType: value.patternType,
        description: value.description,
        entries: from_candid_vec_n42(_uploadFile, _downloadFile, value.entries),
        customPattern: value.customPattern,
        cycleSchemaId: value.cycleSchemaId
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TaskStatus;
    restEntries: Array<_RestEntry>;
    allSubTasksCompleted: boolean;
    description: string;
    subTasks: Array<_SubTaskEntry>;
    taskId: string;
    parentTaskId: [] | [string];
    timeEstimateInMinutes: [] | [bigint];
}): {
    status: TaskStatus;
    restEntries: Array<RestEntry>;
    allSubTasksCompleted: boolean;
    description: string;
    subTasks: Array<SubTaskEntry>;
    taskId: string;
    parentTaskId?: string;
    timeEstimateInMinutes?: bigint;
} {
    return {
        status: from_candid_TaskStatus_n47(_uploadFile, _downloadFile, value.status),
        restEntries: value.restEntries,
        allSubTasksCompleted: value.allSubTasksCompleted,
        description: value.description,
        subTasks: from_candid_vec_n49(_uploadFile, _downloadFile, value.subTasks),
        taskId: value.taskId,
        parentTaskId: record_opt_to_undefined(from_candid_opt_n52(_uploadFile, _downloadFile, value.parentTaskId)),
        timeEstimateInMinutes: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.timeEstimateInMinutes))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TaskStatus;
    description: string;
    subTaskId: string;
    timeEstimateInMinutes: [] | [bigint];
}): {
    status: TaskStatus;
    description: string;
    subTaskId: string;
    timeEstimateInMinutes?: bigint;
} {
    return {
        status: from_candid_TaskStatus_n47(_uploadFile, _downloadFile, value.status),
        description: value.description,
        subTaskId: value.subTaskId,
        timeEstimateInMinutes: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.timeEstimateInMinutes))
    };
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    routineLayerConfig: _RoutineLayerConfig;
} | {
    cycleSchema: _CycleSchema;
} | {
    rest: _RestEntry;
} | {
    task: _TaskDetails;
}): {
    __kind__: "routineLayerConfig";
    routineLayerConfig: RoutineLayerConfig;
} | {
    __kind__: "cycleSchema";
    cycleSchema: CycleSchema;
} | {
    __kind__: "rest";
    rest: RestEntry;
} | {
    __kind__: "task";
    task: TaskDetails;
} {
    return "routineLayerConfig" in value ? {
        __kind__: "routineLayerConfig",
        routineLayerConfig: from_candid_RoutineLayerConfig_n35(_uploadFile, _downloadFile, value.routineLayerConfig)
    } : "cycleSchema" in value ? {
        __kind__: "cycleSchema",
        cycleSchema: from_candid_CycleSchema_n40(_uploadFile, _downloadFile, value.cycleSchema)
    } : "rest" in value ? {
        __kind__: "rest",
        rest: value.rest
    } : "task" in value ? {
        __kind__: "task",
        task: from_candid_TaskDetails_n45(_uploadFile, _downloadFile, value.task)
    } : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notStarted: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): TaskStatus {
    return "notStarted" in value ? TaskStatus.notStarted : "completed" in value ? TaskStatus.completed : "inProgress" in value ? TaskStatus.inProgress : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    task: null;
} | {
    sleep: null;
} | {
    stats: null;
} | {
    routine: null;
} | {
    special: null;
}): TimelineEventType {
    return "task" in value ? TimelineEventType.task : "sleep" in value ? TimelineEventType.sleep : "stats" in value ? TimelineEventType.stats : "routine" in value ? TimelineEventType.routine : "special" in value ? TimelineEventType.special : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TimelineEvent>): Array<TimelineEvent> {
    return value.map((x)=>from_candid_TimelineEvent_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LayerEntry>): Array<LayerEntry> {
    return value.map((x)=>from_candid_LayerEntry_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CycleSchemaEntry>): Array<CycleSchemaEntry> {
    return value.map((x)=>from_candid_CycleSchemaEntry_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SubTaskEntry>): Array<SubTaskEntry> {
    return value.map((x)=>from_candid_SubTaskEntry_n50(_uploadFile, _downloadFile, x));
}
function to_candid_CycleSchemaEntry_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CycleSchemaEntry): _CycleSchemaEntry {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_CycleSchema_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CycleSchema): _CycleSchema {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_LayerEntry_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LayerEntry): _LayerEntry {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_RoutineLayerConfig_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoutineLayerConfig): _RoutineLayerConfig {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_SubTaskEntry_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubTaskEntry): _SubTaskEntry {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_TaskDetails_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskDetails): _TaskDetails {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_TaskStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): _TaskStatus {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_TimelineEventType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimelineEventType): _TimelineEventType {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_TimelineEvent_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimelineEvent): _TimelineEvent {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: TaskStatus;
    restEntries: Array<RestEntry>;
    allSubTasksCompleted: boolean;
    description: string;
    subTasks: Array<SubTaskEntry>;
    taskId: string;
    parentTaskId?: string;
    timeEstimateInMinutes?: bigint;
}): {
    status: _TaskStatus;
    restEntries: Array<_RestEntry>;
    allSubTasksCompleted: boolean;
    description: string;
    subTasks: Array<_SubTaskEntry>;
    taskId: string;
    parentTaskId: [] | [string];
    timeEstimateInMinutes: [] | [bigint];
} {
    return {
        status: to_candid_TaskStatus_n13(_uploadFile, _downloadFile, value.status),
        restEntries: value.restEntries,
        allSubTasksCompleted: value.allSubTasksCompleted,
        description: value.description,
        subTasks: to_candid_vec_n15(_uploadFile, _downloadFile, value.subTasks),
        taskId: value.taskId,
        parentTaskId: value.parentTaskId ? candid_some(value.parentTaskId) : candid_none(),
        timeEstimateInMinutes: value.timeEstimateInMinutes ? candid_some(value.timeEstimateInMinutes) : candid_none()
    };
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: TaskStatus;
    description: string;
    subTaskId: string;
    timeEstimateInMinutes?: bigint;
}): {
    status: _TaskStatus;
    description: string;
    subTaskId: string;
    timeEstimateInMinutes: [] | [bigint];
} {
    return {
        status: to_candid_TaskStatus_n13(_uploadFile, _downloadFile, value.status),
        description: value.description,
        subTaskId: value.subTaskId,
        timeEstimateInMinutes: value.timeEstimateInMinutes ? candid_some(value.timeEstimateInMinutes) : candid_none()
    };
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cycleType: string;
    description: string;
    schemaEntries: Array<CycleSchemaEntry>;
    cycleSchemaId: string;
}): {
    cycleType: string;
    description: string;
    schemaEntries: Array<_CycleSchemaEntry>;
    cycleSchemaId: string;
} {
    return {
        cycleType: value.cycleType,
        description: value.description,
        schemaEntries: to_candid_vec_n20(_uploadFile, _downloadFile, value.schemaEntries),
        cycleSchemaId: value.cycleSchemaId
    };
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    patternType: string;
    description: string;
    entries: Array<CycleSchemaEntry>;
    customPattern: Array<boolean>;
    cycleSchemaId: string;
}): {
    patternType: string;
    description: string;
    entries: Array<_CycleSchemaEntry>;
    customPattern: Array<boolean>;
    cycleSchemaId: string;
} {
    return {
        patternType: value.patternType,
        description: value.description,
        entries: to_candid_vec_n20(_uploadFile, _downloadFile, value.entries),
        customPattern: value.customPattern,
        cycleSchemaId: value.cycleSchemaId
    };
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    layerConfig: LayerEntry;
    routineId: string;
}): {
    layerConfig: _LayerEntry;
    routineId: string;
} {
    return {
        layerConfig: to_candid_LayerEntry_n25(_uploadFile, _downloadFile, value.layerConfig),
        routineId: value.routineId
    };
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    layerId: string;
    subLayers: Array<LayerEntry>;
    description: string;
    layerType: string;
    timeEstimateInMinutes?: bigint;
}): {
    layerId: string;
    subLayers: Array<_LayerEntry>;
    description: string;
    layerType: string;
    timeEstimateInMinutes: [] | [bigint];
} {
    return {
        layerId: value.layerId,
        subLayers: to_candid_vec_n27(_uploadFile, _downloadFile, value.subLayers),
        description: value.description,
        layerType: value.layerType,
        timeEstimateInMinutes: value.timeEstimateInMinutes ? candid_some(value.timeEstimateInMinutes) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    startTime: bigint;
    endTime?: bigint;
    details: {
        __kind__: "routineLayerConfig";
        routineLayerConfig: RoutineLayerConfig;
    } | {
        __kind__: "cycleSchema";
        cycleSchema: CycleSchema;
    } | {
        __kind__: "rest";
        rest: RestEntry;
    } | {
        __kind__: "task";
        task: TaskDetails;
    };
    eventType: TimelineEventType;
}): {
    id: string;
    startTime: bigint;
    endTime: [] | [bigint];
    details: {
        routineLayerConfig: _RoutineLayerConfig;
    } | {
        cycleSchema: _CycleSchema;
    } | {
        rest: _RestEntry;
    } | {
        task: _TaskDetails;
    };
    eventType: _TimelineEventType;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        endTime: value.endTime ? candid_some(value.endTime) : candid_none(),
        details: to_candid_variant_n10(_uploadFile, _downloadFile, value.details),
        eventType: to_candid_TimelineEventType_n28(_uploadFile, _downloadFile, value.eventType)
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "routineLayerConfig";
    routineLayerConfig: RoutineLayerConfig;
} | {
    __kind__: "cycleSchema";
    cycleSchema: CycleSchema;
} | {
    __kind__: "rest";
    rest: RestEntry;
} | {
    __kind__: "task";
    task: TaskDetails;
}): {
    routineLayerConfig: _RoutineLayerConfig;
} | {
    cycleSchema: _CycleSchema;
} | {
    rest: _RestEntry;
} | {
    task: _TaskDetails;
} {
    return value.__kind__ === "routineLayerConfig" ? {
        routineLayerConfig: to_candid_RoutineLayerConfig_n23(_uploadFile, _downloadFile, value.routineLayerConfig)
    } : value.__kind__ === "cycleSchema" ? {
        cycleSchema: to_candid_CycleSchema_n18(_uploadFile, _downloadFile, value.cycleSchema)
    } : value.__kind__ === "rest" ? {
        rest: value.rest
    } : value.__kind__ === "task" ? {
        task: to_candid_TaskDetails_n11(_uploadFile, _downloadFile, value.task)
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): {
    notStarted: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == TaskStatus.notStarted ? {
        notStarted: null
    } : value == TaskStatus.completed ? {
        completed: null
    } : value == TaskStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimelineEventType): {
    task: null;
} | {
    sleep: null;
} | {
    stats: null;
} | {
    routine: null;
} | {
    special: null;
} {
    return value == TimelineEventType.task ? {
        task: null
    } : value == TimelineEventType.sleep ? {
        sleep: null
    } : value == TimelineEventType.stats ? {
        stats: null
    } : value == TimelineEventType.routine ? {
        routine: null
    } : value == TimelineEventType.special ? {
        special: null
    } : value;
}
function to_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<SubTaskEntry>): Array<_SubTaskEntry> {
    return value.map((x)=>to_candid_SubTaskEntry_n16(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CycleSchemaEntry>): Array<_CycleSchemaEntry> {
    return value.map((x)=>to_candid_CycleSchemaEntry_n21(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<LayerEntry>): Array<_LayerEntry> {
    return value.map((x)=>to_candid_LayerEntry_n25(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
